#!/usr/bin/env bash

NAMESPACES=$(kubectl get namespaces -o jsonpath="{.items[*]['metadata.name']}" -l operator=test)
NAMESPACES=$(echo $NAMESPACES | tr " " "\n")

for namespace in  $NAMESPACES
do
  kubectl delete subs --all --wait -n $namespace > /dev/null 2>&1
  kubectl delete csv --all --wait -n $namespace > /dev/null 2>&1
  kubectl delete operatorgroup --all --wait -n $namespace > /dev/null 2>&1
  kubectl delete pod,configmap,deployment,secret,sts --all --wait -n $namespace > /dev/null 2>&1
  kubectl delete namespace --wait $namespace > /dev/null 2>&1
done

