#!/usr/bin/env bash

cd /
set -e

. /scripts/ci/legacy/env
if [[ "$CLEAN_MODE" == "FORCE" ]]; then
  trap_add_exit "uninstall_olm"
  trap_add_exit "delete_namespace $NAMESPACE $CLEAN_MODE"
fi

/scripts/ci/legacy/run-script "/scripts/ci/legacy/install-olm" "Install OLM"
/scripts/ci/legacy/run-script "/scripts/ci/legacy/build-olm-manifests" "Building manifests"

/scripts/ci/legacy/operator-test

if [[ $1 != "false" ]]; then
  /scripts/ci/legacy/instrument-operator
  /scripts/ci/legacy/scorecard
fi