#!/usr/bin/env bash

set -e

# Verifies each operator with changes in a PR with operator-courier.
if [[ -n $OPERATORS_OPENSHIFT ]]; then
  for path_ver in ${OPERATORS_OPENSHIFT}; do
    OP_PATH="$(echo "$path_ver" | cut -d':' -f1)"
    echo "Verifying '$OP_PATH' against operator-courier"
    operator-courier verify "$OP_PATH"
  done
else
  echo "No 'community-operators' modified"
fi

if [[ -n $OPERATORS_UPSTREAM ]]; then
  for path_ver in ${OPERATORS_UPSTREAM}; do
    OP_PATH="$(echo "$path_ver" | cut -d':' -f1)"
    echo "Verifying '$OP_PATH' against operator-courier"
    operator-courier verify --ui_validate_io "$OP_PATH"
  done
else
  echo "No 'upstream-community-operators' modified"
fi
