FROM fedora:34
RUN dnf install python3-pip git mkdocs-material python3-root -y
RUN pip install --no-cache-dir mkpdfs-mkdocs mkdocs-mermaid2-plugin
COPY ci/operator-flow/* /app/
WORKDIR /app
RUN pip3 install -r requirements.txt
CMD ["/bin/bash"]
