#!/usr/bin/env bash

EXECUTABLES="jq yq operator-courier operator-sdk helm kubectl minikube crictl"

for i in $EXECUTABLES
do
    # command -v will return >0 when the $i is not found
    command -v $i >/dev/null && continue || { echo "$i command not found. Need to be installed"; }
done