#!/bin/bash

set -e
unset OP_PATH
unset OP_VER

function setName {
      if [ $(echo $sf| awk -F'/' '{print NF}') -ge 3 ]; then OP_NAME="$(echo "$sf" | awk -F'/' '{ print $2 }')"; fi
      if [ $(echo $sf| awk -F'/' '{print NF}') -ge 4 ]; then OP_VER="$(echo "$sf" | awk -F'/' '{ print $3 }')"; fi
      if [ $(echo $sf| awk -F'/' '{print NF}') -ge 3 ]; then OP_PATH="$(echo "$sf" | awk -F'/' '{ print $1"/"$2 }')"; fi
           }

[ -e /tmp/op_ver ] && rm /tmp/op_ver

if [ "$1" = "release" ]; then
  echo "Running in release mode."
  export PR_COMMIT=$(git log -n1 --format=format:"%H" | tail -n 1)
else
  echo "Running in PR (test) mode."
  #export PR_COMMIT=$(git log -n2 --format=format:"%H" | tail -n 1)
  export PR_COMMIT=$(git --no-pager log --oneline| head -n 1 | awk '{print $3}')
fi
export MODE_CHANGE=0 # targeting ci.yaml

echo "PR_COMMIT=$PR_COMMIT"
echo "git log"
git --no-pager log --oneline|head
echo
echo "Source commit details:"
git --no-pager log -m -1 --name-only --first-parent $PR_COMMIT

export OP_VER_OVERWRITE=0
export OP_RECREATE=0
export PR_NUMBER=$TRAVIS_PULL_REQUEST
echo "Before PR_NUMBER=$PR_NUMBER"
[[ "$PR_NUMBER" == "false" ]] && export PR_NUMBER=$(git --no-pager log --oneline | head -n 1 | cut -d '(' -f 2 | cut -d '#' -f 2 | cut -d ')' -f 1)
echo "After PR_NUMBER=$PR_NUMBER"
if [[ -n "$PR_NUMBER" ]]; then
  for l in $(curl -s https://api.github.com/repos/operator-framework/community-operators/pulls/$REPO | jq '.labels[].name ' -r);do
    echo "Checking lable '$l' ..."
    [[ "$l" = "allow/operator-version-overwrite" ]] && export OP_VER_OVERWRITE=1
    [[ "$l" = "allow/operator-recreate" ]] && export OP_RECREATE=1
  done
fi
echo "PR_NUMBER=$PR_NUMBER OP_VER_OVERWRITE=$OP_VER_OVERWRITE OP_RECREATE=$OP_RECREATE"

declare -A CHANGED_FILES

CHANGED_FILES=$(git --no-pager log -m -1 --name-only --first-parent $PR_COMMIT|awk 'NR > 8 { print }'|grep '/' 2>&1)
echo "CHANGED_FILES:"
echo ${CHANGED_FILES[@]}
echo

UPSTREAM_SET=0
COMMUNITY_SET=0

echo "processing files:"
for sf in ${CHANGED_FILES[@]}; do
  echo $sf

  if [[ $sf == "upstream"* ]]; then
      if [ "$COMMUNITY_SET" -gt "0"  ]; then echo "You are allowed to edit only one stream - upstream-community-operators or community-operators"; exit 1; fi
      export RUN_UPSTREAM=true
      #for run-release
      export STREAM_NAME=upstream-community-operators
      UPSTREAM_SET=1
      setName

  elif [[ $sf == "community"* ]]; then
      if [ "$UPSTREAM_SET" -gt "0"  ]; then echo "You are allowed to edit only one stream - upstream-community-operators or community-operators"; exit 1; fi
      export STREAM_NAME=community-operators
      COMMUNITY_SET=1
      setName

  else
      echo "Edited files outside upstream-community-operators/community-operators !!! "
  fi


done
echo
echo
if [ "$UPSTREAM_SET" -eq "0" ]; then
   if [ "$COMMUNITY_SET" -eq "0" ]; then
     echo "No operator modified, exiting, no need to test/release."; echo; echo;

      cat <<EOF >/tmp/vars-op-path
export NO_OPERATOR=1
export PR_COMMIT=$PR_COMMIT #for traffic light
EOF

     exit 0;
   fi
fi

echo

if [ -z "${OP_PATH+xxx}" ]; then
  echo OP_PATH is not set at all;
#  exit 1
fi

cat <<EOF >/tmp/vars-op-path
export OP_PATH=$OP_PATH
export OP_NAME=$OP_NAME
export OP_VER=$OP_VER
export PR_COMMIT=$PR_COMMIT
export STREAM_NAME=$STREAM_NAME
export RUN_UPSTREAM=$RUN_UPSTREAM
export OP_VER_OVERWRITE=$OP_VER_OVERWRITE
export OP_RECREATE=$OP_RECREATE
export PR_NUMBER=$PR_NUMBER
EOF

echo "exported:"
cat /tmp/vars-op-path