#!/usr/bin/env bash

set -e

unset OP_PATH
unset OP_VER
[ -e /tmp/op_ver ] && rm /tmp/op_ver

OP_PR_COMMIT=$(git log -n1 --format=format:"%H" | tail -n 1)

declare -A OP_TYPES
OP_TYPES=(
  ["upstream"]="upstream-community-operators"
  ["openshift"]="community-operators"
)

# Remove duplicates.
declare -A SEEN
for op_distro in "${!OP_TYPES[@]}"; do
  OP_TYPE_VAR="OPERATORS_${op_distro^^}"
  declare $OP_TYPE_VAR=""
  for op_type in ${OP_TYPES[$op_distro]}; do
    for file in $(git log -m -1 --name-only --first-parent $OP_PR_COMMIT --name-only 2>&1); do
      if echo "$file" | grep -q "^$op_type"; then
        if [ $(echo $file| awk -F'/' '{print NF}') -ge 4 ]; then
            OP_PATH="$(echo "$file" | awk -F'/' '{ print $1"/"$2 }')"
            OP_VER="$(echo "$file" | awk -F'/' '{ print $3 }')"
            echo $OP_VER >> /tmp/op_ver
        fi
#        if [[ -n "${SEEN[$OP_PATH]}" ]]; then
#          continue
#        fi
#        SEEN[$OP_PATH]="seen"
      fi
    done
  done
done
echo "export OP_VER=$(cat /tmp/op_ver 2>/dev/null|  sort --version-sort | tail -n 1)"
echo "export OP_PATH=$OP_PATH"

