#!/usr/bin/env bash

set -e

# Make sure the TRAVIS_COMMIT_RANGE is valid, by catching any errors and exiting.
if [[ -z "$TRAVIS_COMMIT_RANGE" ]] || ! git rev-list --quiet $TRAVIS_COMMIT_RANGE; then
  echo "Invalid commit range."
  exit 0
fi

# Only run CI if an operator package was modified.
if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q '\.yaml'; then
  echo "Only non-manifest files were updated, not running the CI."
  exit 0
fi

# Only run Travis CI on changes to certain directories.
DIRS=( "upstream-community-operators" )
IS_TESTABLE=1
for d in "${DIRS[@]}"; do
  if git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q "$d"; then
    IS_TESTABLE=0
    break
  fi
done
if [[ $IS_TESTABLE -gt 0 ]]; then
  echo "No testable operators were updated, not running the CI."
  exit 0
fi
