#!/usr/bin/env bash
set -e

DIRS=()
GIT_INFO=""

if [[ "$1" == "openshift" ]]; then
  DIRS=( "community-operators" )
else
  DIRS=( "upstream-community-operators" )
fi

GIT_INFO=master

# Only run CI on changes to certain directories.
if git diff --name-only $GIT_INFO | grep -q '\.yaml'; then
  IS_TESTABLE=1
  for d in "${DIRS[@]}"; do
    if git diff --name-only $GIT_INFO | grep -q "$d"; then
      IS_TESTABLE=0
      break
    fi
  done
  if [[ $IS_TESTABLE -gt 0 ]]; then
    echo "No testable operators or scripts were updated, not running the CI."
    exit 0
  fi
elif [[ "$1" == "openshift" ]] || ! git diff --name-only $GIT_INFO | grep -E -q '(\.travis\.yml)|(scripts/ci)|(scripts/lib)'; then
  # Only run CI if an operator package or CI script was modified.
  echo "No manifest or script files were updated, not running the CI."
  exit 0
fi
