#!/usr/bin/env bash

NAMESPACES=$(kubectl get namespaces -o jsonpath="{.items[*]['metadata.name']}" -l operator=test)
NAMESPACES=$(echo $NAMESPACES | tr " " "\n")

for namespace in  $NAMESPACES
do
  kubectl delete subs -l operator=test --wait -n $namespace > /dev/null 2>&1
  kubectl delete operatorgroup -l operator=test --wait -n $namespace --all > /dev/null 2>&1
  kubectl delete pod,configmap,deployment,secret,sts --wait -n $namespace --all > /dev/null 2>&1
  kubectl delete namespace --wait $namespace > /dev/null 2>&1
done

