#!/usr/bin/env bash
DISTRO_TYPE=upstream
ANSIBLE_BASE_ARGS="-i localhost, local.yml -e ansible_connection=local -e run_remove_catalog_repo=false"
ANSIBLE_PULL_REPO="https://github.com/redhat-operator-ecosystem/operator-test-playbooks"
ANSIBLE_PULL_BRANCH="upstream-community"

