#!/usr/bin/env bash

# Try twice, since order matters
curl -L https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.10.0/install.sh --silent -o ./install.sh
chmod +x ./install.sh
./install.sh 0.10.0
rm -rf install.sh

# Delete "operatorhubio-catalog"
kubectl delete catalogsource operatorhubio-catalog -n olm
