#!/usr/bin/env bash

if [[ $(kubectl cluster-info | grep -q 'master is running') ]]; then
  echo 'cluster is running and ready for installing olm'
else
  >&2 echo 'cluster probably not running'
  exit 1
fi

curl -L https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.10.0/install.sh --silent -o ./install.sh
chmod +x ./install.sh
./install.sh 0.10.0

# Delete "operatorhubio-catalog"
kubectl delete catalogsource operatorhubio-catalog -n olm
