#!/usr/bin/env bash

set -e

if [[ -z ${KIND_VER+x} ]]; then
    KIND_VER=latest
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install kind
else
    curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VER}/kind-linux-amd64
    chmod +x ./kind
    mv kind /usr/local/bin/
fi