#!/usr/bin/env bash

set -e

# Don't use sudo when running in a container.
SUDO=sudo
if [ -f /.dockerenv ]; then
  SUDO=
fi

# DISTRO_TYPE is either "upstream" or "openshift"
DISTRO_TYPE_UPSTREAM="upstream"
DISTRO_TYPE_OPENSHIFT="openshift"
DISTRO_TYPE="${1:-$DISTRO_TYPE_UPSTREAM}"
if [[ "$DISTRO_TYPE" != "$DISTRO_TYPE_UPSTREAM" && "$DISTRO_TYPE" != "$DISTRO_TYPE_OPENSHIFT" ]]; then
  echo "DISTRO_TYPE \"$DISTRO_TYPE\" is not valid. Must be one of: \"$DISTRO_TYPE_UPSTREAM\", \"$DISTRO_TYPE_OPENSHIFT\"."
  exit 1
fi

# jq, yq
echo "Installing jq and yq"
curl -Lo jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
chmod +x jq
$SUDO mv jq /usr/local/bin/
curl -Lo yq https://github.com/mikefarah/yq/releases/download/2.2.1/yq_linux_amd64
chmod +x yq
$SUDO mv yq /usr/local/bin/
# operator-courier
echo "Installing operator-courier"
python3 -m pip install operator-courier
# SDK
echo "Installing operator-sdk"
curl -Lo operator-sdk "https://github.com/operator-framework/operator-sdk/releases/download/${SDK_VER}/operator-sdk-${SDK_VER}-x86_64-linux-gnu"
chmod +x operator-sdk
$SUDO mv operator-sdk /usr/local/bin/
# kubectl
echo "Installing kubectl"
curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/${KUBE_VER}/bin/linux/amd64/kubectl"
chmod +x kubectl
$SUDO mv kubectl /usr/local/bin/

if [[ "$DISTRO_TYPE" == "$DISTRO_TYPE_UPSTREAM" ]]; then
  # kind
  echo "Installing kind"
  echo $(uname)
  echo "https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VER}/kind-$(uname)-amd64"
  curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VER}/kind-$(uname)-amd64
  chmod +x kind
  $SUDO mv kind /usr/local/bin/
fi
