#!/usr/bin/env bash


if [[ "$(kubectl api-resources | grep -o operatorgroup)" != "operatorgroup" ]]; then
  operator-sdk olm install --version ${OLM_VER}

  # Delete "operatorhubio-catalog"
  kubectl delete catalogsource operatorhubio-catalog -n olm
fi