#!/usr/bin/env bash


if [[ "$OSTYPE" == "darwin"* ]]; then
    brew cask install minikube
else
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    chmod +x minikube
	mv minikube /usr/local/bin/
fi