#!/usr/bin/env bash


if [[ "$(kubectl api-resources | grep -o operatorgroup)" != "operatorgroup" ]]; then
  operator-sdk alpha olm install > /dev/null 2>&1

  # Delete "operatorhubio-catalog"
  # kubectl delete catalogsource operatorhubio-catalog -n olm > /dev/null
fi