#!/usr/bin/env bash

eval $(scripts/ci/ansible-env)

if [ -n "${OP_PATH}" ];
  then
    echo "Found modified operator. Green light."
    exit 0
  else
    echo "Operator not modified, no need to run tests. Red light."
    exit 1
fi
