#!/usr/bin/env bash

#This will push the application (operator) to Quay appregistry which serves for backwards compatibility

NO_OPERATOR=0 #related to ansible-env
scripts/ci/ansible-env release

if [ -f /tmp/vars-op-path ]; then
    source /tmp/vars-op-path
    if [ "$NO_OPERATOR" -gt "0"  ]; then
     exit 0 # no need to test/release, no operator modified
    fi

    echo $OP_PATH

    echo "$ANSIBLE_PULL_BRANCH is set"

    if [[ $(echo $OP_PATH) = community* ]]; then

        ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS --tags host_build,deploy_bundles -e operator_dir=/tmp/community-operators-for-catalog/$OP_PATH -e quay_appregistry_api_token=$QUAY_APPREG_TOKEN -e quay_appregistry_courier_token=$QUAY_COURIER_TOKEN -e production_registry_namespace=quay.io/openshift-community-operators -e index_force_update=true -e bundle_index_image_name=catalog

    else
        echo "No Openshift community-operators modified, nothing to push to old Quay AppRegistry"; exit 0;
    fi

else
     echo "The file /tmp/vars-op-path does not exist."
     exit 1
fi