#!/usr/bin/env bash

#This will push the application (operator) to Quay appregistry which serves for backwards compatibility

eval $(scripts/ci/app-reg-env)
echo $OP_PATH

echo "$ANSIBLE_PULL_BRANCH is set"

if [[ $(echo $OP_PATH) = community* ]]; then

    ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS --tags host_build,deploy_bundles -e operator_dir=/tmp/community-operators-for-catalog/$OP_PATH -e quay_appregistry_api_token=$QUAY_APPREG_TOKEN -e quay_appregistry_courier_token=$QUAY_COURIER_TOKEN -e production_registry_namespace=quay.io/openshift-community-operators -e index_force_update=true -e bundle_index_image_name=catalog

else
    echo "No Openshift community-operators modified, nothing to push to old Quay AppRegistry"; exit 0;
fi

