#!/usr/bin/env bash


for f in "$(cd "$(dirname ${BASH_SOURCE[0]})/.." && pwd)"/lib/*; do
  . "$f"
done

export_color

printf "${2} %s\t[ ${WARN} Processing ${NC} ]\n" | expand  -t 50


if [[ $VERBOSE == 1 ]]; then
    $1
else
    $1 2>&1  >/dev/null
fi

if [[ $? == 0 ]]; then
    printf "${2} %s\t[ ${OK} OK ${NC} ]\n" | expand  -t 50
else
    printf "${2} %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50
    if [[ ${3} != 'false' ]]; then
      exit 1
    fi
fi
