#!/usr/bin/env bash
set -e #fail in case of non zero return

OHIO_INPUT_CATALOG_IMAGE=${OHIO_INPUT_CATALOG_IMAGE-"quay.io/operatorhubio/catalog:latest"}
OHIO_REGISTRY_IMAGE=${OHIO_REGISTRY_IMAGE-"quay.io/operator-framework/upstream-community-operators:latest"}

ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS \
--tags host_build,app_registry \
-e bundle_index_image=$OHIO_INPUT_CATALOG_IMAGE \
-e index_export_parallel=true \
-e app_registry_image=$OHIO_REGISTRY_IMAGE \
-e quay_api_token=$OHIO_REGISTRY_TOKEN

