#!/usr/bin/env bash
set -e
set -x #temp
#temp host build disabled

#temp
#export AUTOMATION_TOKEN_RELEASE_UPSTREAM=[secure]
#export AUTOMATION_TOKEN_RELEASE_COMMUNITY=[secure]
#export AUTOMATION_TOKEN_RELEASE_UPSTREAM_TEST=[secure]
#export AUTOMATION_TOKEN_RELEASE_COMMUNITY_TEST=[secure]
export ANSIBLE_BASE_ARGS="-i localhost, local.yml -e ansible_connection=local -e run_upstream=true -e run_remove_catalog_repo=false"
export ANSIBLE_CONFIG="$PWD/ansible.cfg"
export ANSIBLE_PULL_BRANCH="upstream-community"
export OHIO_REGISTRY_IMAGE="quay.io/operator-framework/upstream-community-operators:latest"
export CI_OHIO_BRANCH="master"
export ANSIBLE_VERSION="2.10.1"
export ANSIBLE_PULL_REPO="https://github.com/redhat-operator-ecosystem/operator-test-playbooks"
export GODEBUG="x509ignoreCN=0"
export ANSIBLE_EXTRA_ARGS="-e operator_courier_version=2.1.11"
export OHIO_INPUT_CATALOG_IMAGE="quay.io/operatorhubio/catalog:latest"
export OHIO_REGISTRY_IMAGE="quay.io/operator-framework/upstream-community-operators:dev"
export CI_OHIO_BRANCH="dev"
#export CI_OHIO_TRIGGER_TOKEN=[secure]
#export OHIO_REGISTRY_TOKEN=[secure]
export OHIO_INPUT_CATALOG_IMAGE="quay.io/openshift-community-operators/catalog:latest"
export COMMUNITY_SPECIAL='-e use_cluster_filter=true'


OPENSHIFT_VERSION_DEFAULTS='4.6 4.7' #space delimited
INDEX_CHECK_PARAMS=''
AUTH_PARAMS=''
GENERATE_OP_CONF=1
FORCE_RELEASE=0
MODE_CHANGE=${MODE_CHANGE-0}
OP_DELETE=${OP_DELETE-0}
OP_DEBUG=${OP_DEBUG-0}
OP_UNCOMPLETE=/tmp/operators_uncomplete-localhost.yaml
MY_OP_BASE_DIR="/tmp/oper/community-operators"

case "$1" in

-u)  echo "Index fix upstream pipeline"
        STREAM_NAME='upstream-community-operators'
        INDEX_CHECK_PARAMS='-e operator_base_dir='$MY_OP_BASE_DIR'/'$STREAM_NAME' -e bundle_index_image=quay.io/operatorhubio/catalog'
        AUTH_PARAMS='-e quay_api_token='$AUTOMATION_TOKEN_RELEASE_UPSTREAM' -e bundle_registry=quay.io -e bundle_image_namespace=operatorhubio -e bundle_index_image_namespace=operatorhubio -e bundle_index_image_name=catalog'
        BUNDLE_FORCE_PARAMS="-e production_registry_namespace=quay.io/operatorhubio"
        CLUSTER_VERSION_LIST='latest'
    ;;
-c)  echo "Index fix community pipeline"
        STREAM_NAME='community-operators'
        INDEX_CHECK_PARAMS='-e operator_base_dir='$MY_OP_BASE_DIR'/'$STREAM_NAME' -e bundle_index_image=quay.io/openshift-community-operators/catalog'
        # AUTH_PARAMS="-e quay_api_token=$AUTOMATION_TOKEN_RELEASE_COMMUNITY -e bundle_registry=quay.io -e bundle_image_namespace=openshift-community-operators -e bundle_index_image_namespace=openshift-community-operators -e bundle_index_image_name=catalog -e mirror_index_images=quay.io/redhat/redhat----community-operator-index|redhat+iib_community|$QUAY_RH_INDEX_PW"
        AUTH_PARAMS="-e quay_api_token=$AUTOMATION_TOKEN_RELEASE_COMMUNITY -e bundle_registry=quay.io -e bundle_image_namespace=openshift-community-operators -e bundle_index_image_namespace=openshift-community-operators -e bundle_index_image_name=catalog"
        # BUNDLE_FORCE_PARAMS="-e production_registry_namespace=quay.io/openshift-community-operators -e mirror_index_images=quay.io/redhat/redhat----community-operator-index|redhat+iib_community|$QUAY_RH_INDEX_PW"
        BUNDLE_FORCE_PARAMS="-e production_registry_namespace=quay.io/openshift-community-operators"
        CLUSTER_VERSION_LIST=$OPENSHIFT_VERSION_DEFAULTS
    ;;
*) echo "Syntax: $0 [-u|c]"
   echo "options:"
   echo "u     upstream - Run index fix upstream pipeline"
   echo "c     community - Run index fix community pipeline"
   echo

esac

[[ $OP_DEBUG -eq 1 ]] && VERBOSITY="-v"
[[ $OP_DEBUG -eq 2 ]] && VERBOSITY="-vv"

# In case one adds stream/operator/version as second parameter
if [ -n "$2" ];then
  MY_OP_STREAM=$(echo $2 | cut -d '/' -f 1)
  MY_OP_NAME=$(echo $2 | cut -d '/' -f 2)
  MY_OP_VER=$(echo $2 | cut -d '/' -f 3)

  if [ -n "$MY_OP_STREAM" ] && [ -n "$MY_OP_NAME" ];then
    if  [ ! -z $MY_OP_VER ]; then
      echo "Fixing bundle and index for operator '$2' ..."
#      ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS $VERBOSITY --tags host_build,deploy_bundles \
      ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS $VERBOSITY --tags deploy_bundles \
      -e operator_dir=$MY_OP_BASE_DIR/$MY_OP_STREAM/$MY_OP_NAME -e operator_version=$MY_OP_VER $BUNDLE_FORCE_PARAMS $AUTH_PARAMS -e bundle_force_rebuild=true -e operator_base_dir=/tmp/community-operators-for-catalog/community-operators #temp
      exit 0
    else
      if [[ $OP_DELETE -eq 1 ]];then
        echo "Removing operator '$2' form index ..."
#        ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS $VERBOSITY --tags host_build,remove_operator \
        ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS $VERBOSITY --tags remove_operator \
        -e operator_dir=$MY_OP_BASE_DIR/$MY_OP_STREAM/$MY_OP_NAME $BUNDLE_FORCE_PARAMS $AUTH_PARAMS -e operator_base_dir=/tmp/community-operators-for-catalog/community-operators #temp
        exit 0
      else
        echo "Trying to delete operator $2 !!! Define 'export OP_DELETE=1' to perform delete "
        exit 1
      fi
    fi
  else
    echo "Error: stream/operator/version '$2' is not defined correctly !!! "
    exit 1
  fi

else
  for CLUSTER_VERSION in $CLUSTER_VERSION_LIST; do
    echo "Only update graph mode with no version change: MODE_CHANGE=$MODE_CHANGE"

    echo "Index fix pipeline starting"
    rm -f $OP_UNCOMPLETE
    if [[ $MODE_CHANGE -eq 0 ]] ; then
#      ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS $VERBOSITY --tags host_build,index_check $INDEX_CHECK_PARAMS':'$CLUSTER_VERSION
      ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS $VERBOSITY --tags index_check $INDEX_CHECK_PARAMS':'$CLUSTER_VERSION
    else
      echo "operator_base_dir: $(pwd)/$STREAM_NAME\noperators" > "$OP_UNCOMPLETE"
      echo "operators:" >> "$OP_UNCOMPLETE"
      echo "- $OP_NAME" >> "$OP_UNCOMPLETE"
#      ANSIBLE_EXTRA_TAGS="host_build,"
    fi
    if [ -f $OP_UNCOMPLETE ];then
      cat $OP_UNCOMPLETE
      ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS $VERBOSITY --tags ${ANSIBLE_EXTRA_TAGS}deploy_bundles -e operators_config=$OP_UNCOMPLETE $AUTH_PARAMS -e index_force_update=true -e strict_mode=true $COMMUNITY_SPECIAL
    fi
  done
fi
