#!/usr/bin/env bash

eval $(scripts/ci/ansible-env)

if [ -n "${OP_PATH}" ] ;
  then
    echo "Release pipeline not running for PR, found modified operator."
    exit 0
  fi

echo "Release pipeline starting"
rm /tmp/changed-git* 2>/dev/null
pwd
ls
#mkdir -p /tmp/oper
#cd /tmp/oper
#git clone --depth=50 -n https://github.com/operator-framework/community-operators.git
#cd community-operators
git log --pretty=format: --name-only --since="8 days ago" | sort | uniq > /tmp/changed-git-files
grep upstream-community-operators /tmp/changed-git-files > /tmp/changed-git-files-upstream
cat /tmp/changed-git-files-upstream
if [ $(cat /tmp/changed-git-files-upstream|wc -l) -gt 0 ]; then
    # ignore specific files in upstream-community-operators top level like OWNERS
    awk -F '/' 'NF>2 {print}' /tmp/changed-git-files-upstream > /tmp/changed-git-files-upstream-top-lev
    awk -F 'upstream-community-operators/' '{ print $2 }' /tmp/changed-git-files-upstream-top-lev > /tmp/changed-git-files-upstream-list
    awk -F '/' '{ print $1 }' /tmp/changed-git-files-upstream-list|sort|uniq > /tmp/changed-git-files-upstream-opnames
    sed 's/^/- /' /tmp/changed-git-files-upstream-opnames > /tmp/changed-operators.yaml
    sed -i "1ioperator_base_dir: $(pwd)/upstream-community-operators\noperators:" /tmp/changed-operators.yaml
    CHANGED_OPERATORS=`cat /tmp/changed-operators.yaml`
else
    CHANGED_OPERATORS=''
    echo "Nothing to release"
    exit 0
fi
echo "Input config:"
echo "$CHANGED_OPERATORS"

pwd
ls
##prepre prerequisities
#ansible-pull -U $PLAYBOOK_REPO -C $PLAYBOOK_BRANCH $PLAYBOOK_VARS -e run_upstream=true --tags host_build

#fast run, only bundle/index handling using tags
ansible-pull -U $PLAYBOOK_REPO -C $PLAYBOOK_BRANCH $PLAYBOOK_VARS -e run_upstream=true --tags host_build,deploy_bundles -e operators_config=/tmp/changed-operators.yaml -e operator_channel_force=stable