#!/usr/bin/env bash


for f in "$(cd "$(dirname ${BASH_SOURCE[0]})/.." && pwd)"/lib/*; do
  . "$f"
done

export_color

if [[ $VERBOSE == 1 ]]; then
    $1
else
    $1 2>&1  >/dev/null
fi

if [[ $? == 0 ]]; then
    printf "${2} %s\t[ ${OK} OK ${NC} ]\n" | expand  -t 30
else
    printf "${2} %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 30
fi