#!/usr/bin/env bash
set -e

NO_OPERATOR=0 #related to ansible-env
INPUT_ENV_SCRIPT=${INPUT_ENV_SCRIPT-"/tmp/vars-op-path"}
scripts/ci/ansible-env || { echo "Error in preparing operator environment !!! Contact admins."; exit 1; }

source $INPUT_ENV_SCRIPT

# echo "STREAM_NAME=$STREAM_NAME OP_NAME=$OP_NAME OP_VER=$OP_VER"
# echo "OP_PR_NUMBER=$OP_PR_NUMBER OP_VER_OVERWRITE=$OP_VER_OVERWRITE OP_RECREATE=$OP_RECREATE OP_FORCE_DEPLOY_ON_K8S=$OP_FORCE_DEPLOY_ON_K8S"
if [ -z "${OP_PATH}" ];then
  echo "No operator modification detected. Done with testing."
  exit 0
else
  if [ -z "$OP_VER" ];then
    echo "Error: Operator version was not detected from OP_PATH='$OP_PATH' !!!"
    exit 1
  else
    echo "Detected modified Operator in ${OP_PATH}"
    echo "Detected modified Operator version ${OP_VER}"
    echo "Additional info : "
    echo "        STREAM_NAME=$STREAM_NAME"
    echo "        OP_NAME=$OP_NAME"
    echo "        OP_VER=$OP_VER"
    echo "        OP_PR_NUMBER=$OP_PR_NUMBER"
    echo "        OP_VER_OVERWRITE=$OP_VER_OVERWRITE"
    echo "        OP_RECREATE=$OP_RECREATE"
    echo "        OP_FORCE_DEPLOY_ON_K8S=$OP_FORCE_DEPLOY_ON_K8S"
  fi
fi

# Handle production registry for orange test
if [ "$STREAM_NAME" = "upstream-community-operators" ];then
  CHECK_WITH='-e production_registry_namespace=quay.io/operatorhubio'
else
  CHECK_WITH='-e production_registry_namespace=quay.io/openshift-community-operators'
fi

# Skipping deployment for openshift (when it is not forced by 'test/force-deploy-on-kubernetes')
[ "$STREAM_NAME" = "community-operators" ] && [[ $OP_FORCE_DEPLOY_ON_K8S -eq 0 ]] && EXTRA="-e test_skip_deploy=true"
[[ $OP_VER_OVERWRITE -eq 1 ]] && EXTRA="$EXTRA -e index_force_update=true"
[[ $OP_RECREATE -eq 1 ]] && EXTRA="$EXTRA -e index_force_update=true"

# Runs test
ansible-pull -U $ANSIBLE_PULL_REPO -C $ANSIBLE_PULL_BRANCH $ANSIBLE_BASE_ARGS $ANSIBLE_EXTRA_ARGS \
-e operator_dir=$(pwd)/$OP_PATH \
-e operator_version=$OP_VER \
-e catalog_repo_dir=$(pwd) \
--tags host_build,pure_test \
$CHECK_WITH $EXTRA

echo "All done OK."
