#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  if [[ -z ${VM_DRIVER+x} ]]; then
      VM_DRIVER=hyperkit
  fi
fi

if [[ -n "${KUBE_VER}" ]]; then
    MINIKUBE_KUBE_VERSION="--kubernetes-version="${KUBE_VER}""
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  minikube start --vm-driver=${VM_DRIVER} ${MINIKUBE_KUBE_VERSION} --extra-config=apiserver.v=4
elif
  CHANGE_MINIKUBE_NONE_USER=true sudo minikube start --vm-driver=${VM_DRIVER} ${MINIKUBE_KUBE_VERSION} --extra-config=apiserver.v=4
fi