#!/usr/bin/env bash

set -e

if [ -z "${KUBE_VER}" ] ; then
  KIND_KUBE_VERSION=""
else
  KIND_KUBE_VERSION="--image kindest/node:${KUBE_VER}"
fi

if [ ! -z ${VERBOSE+x} && "${VERBOSE}" == "1" ] ; then
  KIND_VERBOSITY="--verbosity 1"
else
  KIND_VERBOSITY="--verbosity 0"
fi

kind create cluster --name operator-test --wait 1m ${KIND_KUBE_VERSION} ${KIND_VERBOSITY}