#!/usr/bin/env bash

set -e

# Runs scripts/ci/test-operator on each operator with changes in a PR.

DIR="$(cd "$(dirname ${BASH_SOURCE[0]})" && pwd)"
: ${CI_OPERATORS_UPSTREAM:?"CI_OPERATORS_UPSTREAM is not set"}
for path_ver in $CI_OPERATORS_UPSTREAM; do
  OP_PATH="$(echo "$path_ver" | cut -d':' -f1)"
  OP_VER="$(echo "$path_ver" | cut -d':' -f2)"
  "${DIR}/test-operator" "$OP_PATH" "$OP_VER"
done
