#!/usr/bin/env bash

set -e

# Check whether only scripts have been updated, and if so use
# the jaeger operator as an operator to test script correctness.

DISTRO_TYPE_UPSTREAM="upstream"
DISTRO_TYPE_OPENSHIFT="openshift"
DISTRO_TYPE="${1:-$DISTRO_TYPE_UPSTREAM}"
if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q '\.yaml'; then
  echo "No operator manifest changes detected, assuming script updates."
  echo "Running CI with jaeger operator to test scripts"
  OPERATORS_UPSTREAM="upstream-community-operators/jaeger:$(yq r --tojson upstream-community-operators/jaeger/jaeger.package.yaml "channels" \
  | jq ".[] | .currentCSV" | sort -V | tail -1 | sed -E 's/"[a-zA-Z\-]+\.?v?([0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?)"/\1/')" \
  scripts/ci/test-pr $DISTRO_TYPE && exit 0
fi
