#!/usr/bin/env bash

cd /
set -e

. /scripts/ci/env
if [[ "$CLEAN_MODE" == "FORCE" ]]; then
  trap_add_exit "uninstall_olm"
  trap_add_exit "delete_namespace $NAMESPACE $CLEAN_MODE"
fi

/scripts/ci/run-script "/scripts/ci/install-olm" "Install OLM"
/scripts/ci/run-script "/scripts/ci/build-registry-image" "Make registry configmap"
/scripts/ci/run-script "/scripts/ci/operator-test" "Operator deployment"
if [[ $1 != "false" ]]; then
  /scripts/ci/run-script "/scripts/ci/scorecard" "Test operator with scorecard"
fi