#!/usr/bin/env bash

eval $(scripts/ci/ansible-env)

if [ -n "${OP_PATH}" ] ;
  then
    echo "Release pipeline not running for PR, found modified operator."
    exit 0
  fi

echo "Release - just functional test"

echo "operator_base_dir: $(pwd)/upstream-community-operators" > /tmp/tester.yaml

cat <<EOT >> /tmp/tester.yaml
operators:
- akka-cluster-operator
EOT

#prepre prerequisities
ansible-pull -U $PLAYBOOK_REPO -C $PLAYBOOK_BRANCH $PLAYBOOK_VARS -e run_upstream=true  --tags host_build

echo "Input config:"
cat /tmp/tester.yaml

#fast run, only bundle/index handling using tags
ansible-pull -U $PLAYBOOK_REPO -C $PLAYBOOK_BRANCH $PLAYBOOK_VARS -e run_upstream=true --tags deploy_bundles -e operators_config=/tmp/tester.yaml -e operator_channel_force=stable