#!/usr/bin/env bash

set -e

# Verifies each operator with changes in a PR with operator-courier.

: ${CI_OPERATORS_OPENSHIFT:?"CI_OPERATORS_OPENSHIFT is not set"}
for path_ver in $CI_OPERATORS_OPENSHIFT; do
  OP_PATH="$(echo "$path_ver" | cut -d':' -f1)"
  echo "# Verifying '$OP_PATH' against operator-courier"
  operator-courier verify "$OP_PATH"
done

: ${CI_OPERATORS_UPSTREAM:?"CI_OPERATORS_UPSTREAM is not set"}
for path_ver in $CI_OPERATORS_UPSTREAM; do
  OP_PATH="$(echo "$path_ver" | cut -d':' -f1)"
  echo "# Verifying '$OP_PATH' against operator-courier"
  operator-courier verify --ui-validate-io "$OP_PATH"
done
