#!/usr/bin/env bash

function trap_add_exit() {
  local new_trap_cmd="$1"
  local old_trap_cmd="$(trap -p EXIT | awk -F"'" '{ print $2 }')"
  [[ -z "$old_trap_cmd" ]] && old_trap_cmd="date"
  trap "${old_trap_cmd}; ${new_trap_cmd}" EXIT
}
