#!/usr/bin/env bash

function trap_add_exit() {
  local new_trap_cmd="$1"
  local old_trap_cmd="$(trap -p EXIT | awk -F"'" '{ print $2 }')"
  [[ -z "$old_trap_cmd" ]] && old_trap_cmd="date"
  trap "${new_trap_cmd}; ${old_trap_cmd}" EXIT
}

function export_color() {
    OK="\033[0;32m"
    WARN="\033[0;33m"
    ERR="\033[0;31m"
    NC="\033[0m"
}